### ISSUE TITLE
Questions about itaca running on linux

### ISSUE THREAD

**Issue by yangyang1018** [medusabci/medusa-platform#66]
@dmarcos97 
Hello,

We are currently attempting to execute both Medusa and the feedback training module within the ITACA suite on a Linux system. Upon reviewing the source code, we've noticed that the feedback training component utilizes .exe files, which are not natively compatible with Linux environments.

We would greatly appreciate your expertise in this matter. Could you kindly provide us with any potential solutions or suggestions to overcome this compatibility issue? Your guidance would be immensely valuable to us.

Thank you in advance for your time and assistance.

**Comment by esantamariavazquez** [comment]
Hi @yangyang1018,

Thank you for reaching out. At the moment, we officially support only Windows systems for both Medusa and ITACA suite due to specific differences between platforms. Testing everything on Windows and Linux is time-consuming. We recommend running the software in a Windows environment, either directly or through a virtual machine.

That said, we are open to work on a solution for your team and start supporting Linux for some applications. We could provide the ITACA's Unity module compiled for Linux. Could you provide more details of your adaptation of MEDUSA to Linux? Did you have to fix code to run it? Have you tested all features? (e.g., real time plots, LSL connection, etc). 

Best regards,
Eduardo.

**Comment by yangyang1018** [comment]
Dear,@esantamariavazquez 
Thank you very much for your previous insights. I appreciate your assistance. Currently, we are in the process of running MEDUSA on a Linux system. We've encountered a challenge with the LSL-signal-generator, which is not compatible with our Linux environment. To address this, we have developed a script to emulate the EEG signal as per the LSL-signal-generator's source code, thereby creating a simulated LSL stream. We are pleased to report that MEDUSA has successfully received these LSL signals. However, we have yet to explore further testing due to the presence of .exe files in other components, which are not compatible with our Linux setup.

Regarding MEDUSA's dependent environment configuration on Linux, we faced some initial hurdles but have since managed to resolve them. We would be more than happy to share our solutions if they might be of help to others. As for itaca, we have not yet been able to successfully conduct tests due to the aforementioned .exe compatibility issue. We are currently seeking valuable advice from your esteemed team to overcome this obstacle.

Your expertise in this area would be greatly appreciated, and any guidance you could offer would be invaluable to our efforts. Thank you in advance for considering our request.

**Comment by dmarcos97** [comment]
Dear @yangyang1018 

Thank you for your interest in using ITACA for your research. As @esantamariavazquez previously mentioned, we are not providing Linux support yet. However, I managed to build the Unity applications in Linux so that you can use ITACA in your computer. Note that I do not work with Linux, so I have no tested if everything works well. The Linux files have been included in the unity folder (where the .exe files are placed) in the new version of the ITACA app that is available at our web site. Please, let us know if this solution is working correctly.
